name: CI

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew assemble
      - run: ./gradlew ktlintCheck
      - uses: ./.github/workflows/reportLintResults
      - run: ./gradlew test
      - uses: actions/upload-artifact@v3
        with:
          path: '**/*.apk'
      - uses: yumemi-inc/comment-pull-request@v1
        if: cancelled() != true
        with:
          comment: 'CI passed.'
          comment-if-failure: 'CI failed.'
